services:
 web:
  image: nginx
  container_name: nginx_container
  ports:
   - "8080:80"
  networks:
   - frontend
 web-server:
  image: httpd
  container_name: httpd_container
  ports:
   - "8081:80"
  networks:
   - frontend
 web2:
  image: nginx
  container_name: nginx_container_2
  ports:
   - "8082:80"
  networks:
   - frontend


networks:
  frontend:
    name: my_network
    driver: bridge
