services:
  web:
    build: .
    ports:
      - "8009:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"

  redis:
    image: "redis:alpine"
    ports: 
     - "6379:6379"


# redis volume to persist storage

    volumes:
     - redis-data:/data


volumes:
  redis-data:
   driver: local
