services:
  web:
    container_name: flask
    build: .
    ports:
      - "8009:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"

  database:
    image: "redis:alpine"
#    container_name: redis
#    ports: 
#     - "6379:6379"


# redis volume to persist storage

    volumes:
     - redis-data:/data


volumes:
  redis-data:
   driver: local
